config/routes.rb
Korepetytor::Application.routes.draw do

 

  devise_for :users , :path => 'konto' #TODO: nazwy akcji 
     
  
  resources :users, :path => "uzytkownik",  :only => [] do
    resources :comments,  :path => "komentarze", :only => [:update, :edit, :index], :path_names => { :edit => "wystaw" } 
    resource :room,  :path => "pokoj"
    resource :tutor ,  :path => "korepetytor", :path_names => { :new => "zostan", :edit => "edytuj" } 
    resources :payment_histories, :only => [:create]
    resource :payment_management,  :path => "moje_platnosci", :only => [:show]
    resource :my_profile, :path => "moj_profil", :only => :show
  end
 
  resources :messages, :only => [:create]
  resources :contacts, :only => [:create]

  resources :tutors, :path => "korepetytor", :only => [:show] do
    resource :private_room, :path => "prywatna_lekcja" do
      member do
        get :annouce
      end
    end
    resources :comments,  :path => "komentarze",  :only => [:index]
    member do
      put :online
    end
    
  end
  
  resources :subjects, :path => "przedmioty", :only => [:index, :show] do
    resources :tutors, :path => "korepetytorzy", :only => [:index]
  end
  
  resources :payment_notifications, :only => :create

  resources :search_resoults, :path => "szukam", :only => [:index]

  resources :welcomes, :path => "jaktodziala", :only => [:index]

  root :to => 'subjects#index'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id              :integer          not null, primary key
#  sender_id       :integer
#  tutor_id        :integer
#  private_room_id :integer
#  rate            :integer
#  content         :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Comment < ActiveRecord::Base
  
  begin :attributes
    attr_accessible :content, :rate
  end
  
  begin :relations 
    belongs_to :tutor
    belongs_to :user, :foreign_key => "sender_id"
  end
  
  scope :unpublished, lambda { |user_id| where("sender_id = ? AND rate IS NULL", user_id) }
  scope :published, where("rate IS NOT NULL") 
  
  begin :validations
    validates :content,             :presence => true ,  :allow_blank => false,  :allow_nil => false, 
      :length => {:maximum => 150,  :allow_blank => false, :allow_nil => false} 
                                  
    validates :rate,                :presence => true  ,  :allow_blank => false,  :allow_nil => false   
  end
  
  public
  
  def self.prepare_empty_comment!(tutor, learner, private_room)
    unless self.comment_for_lesson_exist?(private_room)
      c =  self.new
      c.tutor_id = tutor
      c.sender_id = learner
      c.private_room_id = private_room
      c.save!(:validate => false)
    end
    
  end

  
  private
  
  def self.comment_for_lesson_exist?(private_room)
    true if self.find_by_private_room_id(private_room)   
  end
  
  
end

app/controllers/comments_controller.rb
# encoding: utf-8
# #!/bin/env ruby
class CommentsController < ApplicationController
  before_filter :access_control, :only => [ :edit, :update ]
  def edit
    @comment = Comment.find_by_id(params[:id])
    @tutor = @comment.tutor
    @comment.update_attributes(params[:comment])
  end
  
  def update
    @comment = Comment.find_by_id(params[:id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        @comment.tutor.new_comment_handler!(@comment.rate)
        flash[:success] = "Pomyślnie dodano komentarz."
        format.html { redirect_to user_comments_path(current_user) }
      else
        format.html { render :action => "edit" } 
      end
    end
  end

  def index
    
    if params[:user_id].present?
      access_control
      @user = User.find_by_id(params[:user_id])      
      @comments = Comment.unpublished(@user.id)
      
    elsif params[:tutor_id].present?
      @tutor = Tutor.find_by_id(params[:tutor_id])
      @comments = @tutor.comments.published.includes(:user)
    end

  end
  
  private
  

  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
=form_for(@comment, :url => user_comment_url(current_user, @comment),  :html => {  :class => "form-horizontal" }) do |f|
  .control-group
    =f.label :rate, "Ocena(1-5):", class: "control-label"  
    .controls
      = f.text_field :rate
      = errors_for f, :rate
  .control-group
    = f.label :content, "Komentarz: (max 150 znaków)", class: "control-label" 
    .controls
      = f.text_area :content, :rows => 8
      = errors_for f, :content

  .control-group
    .controls
      = f.submit "Zatwierdź", class: "btn btn-primary"

app/views/comments/_not_put_up.index.html.haml
- content_for :title do
  ="Wystaw komentarze korepetytorom"
.contentBackground
  %legend
    Oceń prywatne lekcje w których brałeś udział:
  .listAreaComments
    %h4
      W tym miejscu możesz ocenić i wystawić komentarz korepetytorowi po skończonej płatnej lekcji.
    - if @comments.empty?
      Obecnie ta lista jest pusta, wróć tutaj ponownie gdy skończysz płatną lekcję z korepetytorem
    -else
      - @comments.each do |comment|
        .listElement
          Prywatna lekcja u użytkownika
          %strong
            =link_to comment.tutor.user.nickname, user_tutor_path(comment.tutor)
          %br
          %small
            =comment.created_at.strftime("w dniu %d-%m-%Y o godzinie %H:%M ")
            %br
            .listLink
              = link_to "Wystaw komentarz",  edit_user_comment_path(current_user, comment)
            .listLink 
              = link_to "Wyświetl profil #{comment.tutor.user.nickname}",  user_tutor_path(comment.tutor)

app/views/comments/_put_up.index.html.haml
- content_for :title do
  ="Opinie wystawione użytkownikowi #{@tutor.user.nickname}"
.contentBackground
  %legend
    Opinie wystawione użytkownikowi #{@tutor.user.nickname}:
    %small  
      |
      = link_to "Wyświetl profil",  user_tutor_path(@tutor)
      |
      -if @tutor.online?
        = link_to "Przejdź do pokoju", user_room_path(@tutor.user)
        |
  %h4
    #{@tutor.comments_count} opini, średnia ocen #{@tutor.rating} 
  .listAreaComments
    - @comments.each do |comment|
      .listElement
        %small
          Prywatna lekcja z 
          %strong
            =comment.user.nickname
          =comment.created_at.strftime("w dniu %d-%m-%Y")
        %br
        Uczeń skomentował lekcję:
        .listComment
          Ocena:
          = image_tag(star_rating(comment.rate))
        .listComment
          %blockquote
            =comment.content
       
  .clear

app/views/comments/edit.html.haml
- content_for :title do
  ="Wystaw komentarz - @tutor.user.nickname"
.contentBackground
  %legend
    Oceń prywatną lekcje u użytkownika #{@tutor.user.nickname} #{@comment.created_at.strftime("w dniu %d-%m-%Y o godzinie %H:%M ")}
  = render :partial => 'form'

app/views/comments/index.html.haml
//W zalezności od linku, wyświetla komentarze jakie użytkownik może wystawić(:user_id)    lub    komentarze wystawione korepetytorowi (:tutor_id)
-if params[:user_id].present?
  = render :partial => 'not_put_up.index'
- else
  = render :partial => 'put_up.index'