config/routes.rb
Korepetytor::Application.routes.draw do

 

  devise_for :users , :path => 'konto' #TODO: nazwy akcji 
     
  
  resources :users, :path => "uzytkownik",  :only => [] do
    resources :comments,  :path => "komentarze", :only => [:update, :edit, :index], :path_names => { :edit => "wystaw" } 
    resource :room,  :path => "pokoj"
    resource :tutor ,  :path => "korepetytor", :path_names => { :new => "zostan", :edit => "edytuj" } 
    resources :payment_histories, :only => [:create]
    resource :payment_management,  :path => "moje_platnosci", :only => [:show]
    resource :my_profile, :path => "moj_profil", :only => :show
  end
 
  resources :messages, :only => [:create]
  resources :contacts, :only => [:create]

  resources :tutors, :path => "korepetytor", :only => [:show] do
    resource :private_room, :path => "prywatna_lekcja" do
      member do
        get :annouce
      end
    end
    resources :comments,  :path => "komentarze",  :only => [:index]
    member do
      put :online
    end
    
  end
  
  resources :subjects, :path => "przedmioty", :only => [:index, :show] do
    resources :tutors, :path => "korepetytorzy", :only => [:index]
  end
  
  resources :payment_notifications, :only => :create

  resources :search_resoults, :path => "szukam", :only => [:index]

  resources :welcomes, :path => "jaktodziala", :only => [:index]

  root :to => 'subjects#index'

end

app/controllers/payment_managements_controller.rb
# encoding: utf-8
# #!/bin/env ruby
class PaymentManagementsController < ApplicationController
  before_filter :access_control

  def show

    @user = find_user(params[:user_id])
  end  
  
  private
  
  def find_user(user_id)
    User.find_by_id(user_id)
  end

end

app/helpers/payment_managements_helper.rb
module PaymentManagementsHelper
end

app/views/payment_managements/show.html.haml
- content_for :title do
  Moje Płatności
.contentBackground.threeFourSize
  %legend
    Moje Płatności
  .roomControl
    %small
      Do korzystania z płatnych lekcji u korepetytorów wymagana jest wirtualna waluta: ORDERY
      %br
      Standardowa cena za 15min to JEDEN order. 
      %br
      Korepetytor może zwiększyć stawkę, więc sprawdź cenę przed przystąpieniem do płatnej lekcji.
  .clear
  .dataBox
    %strong
      Posiadane ordery:
    .orders
      %span.ordersColor
        =@user.token
      %small
        -if @user.has_tokens?
          czyli #{@user.token_to_minutes} minut w standardowej cenie.
        -else
          Nie masz żadnych orderów.

  .dataBox
    -if @user.tutor?
      %strong
        Wypłać pieniądze za ordery:
      .space.clear
      .roomControl
        %small
          Kurs wymiany to #{CONST[:price_sell_order]}PLN za
          %span.ordersColor="1 order"
      .space.clear
      .roomControl
        %small
          Uwaga! Ordery, które chcesz wymienić muszą być na Twoim koncie minimum przez tydzień.
      .space.clear
      .roomControl
        %small
          Procedura otrzymania pieniędzy.
          %br
          1. Skorzystaj z poniższego formularza wpisując ile orderów chcesz wymienić oraz dane do przelewu.         
          %br
          2. W celu zapewnienia bezpiecznych transakcji żądanie przelewu jest weryfikowane przez pracownika.
          %br
          3. Po weryfikacji wykonywany jest przelew oraz wysyłane potwierdzenie na adres email.
      .clear.space
        .box
          = render :partial => '/contacts/form.contact'
    -else
      %strong
        Kup ordery:

      .buy
        .orders
          %span.ordersColor="1"
          (15 minut) za #{CONST[:price_buy_order]}PLN
          = form_tag(CONFIG[:paypal_url], :class => "styledFormMini" ) do 
            = hidden_field_tag :cmd, "_s-xclick"
            = hidden_field_tag :encrypted, current_user.paypal_encrypted("15 minut prywatnej lekcji", CONST[:price_buy_order], current_user , root_url, payment_notifications_url(:secret =>  CONFIG[:paypal_secret], :tokens => 1))
            = submit_tag "Kup", class: "btn square"

      .buy
        .orders
          %span.ordersColor="4"
          (1 godzina) za #{CONST[:price_buy_order] * 4}PLN
          = form_tag(CONFIG[:paypal_url], :class => "styledFormMini" ) do 
            = hidden_field_tag :cmd, "_s-xclick"
            = hidden_field_tag :encrypted, current_user.paypal_encrypted("1 godzina prywatnej lekcji", CONST[:price_buy_order] * 4 , current_user , root_url, payment_notifications_url(:secret =>  CONFIG[:paypal_secret], :tokens => 4))
            = submit_tag "Kup", class: "btn square" 


      .buy
        .orders
          %span.ordersColor="16"
          (4 godziny) za #{CONST[:price_buy_order] * 16}PLN
          = form_tag(CONFIG[:paypal_url], :class => "styledFormMini" ) do 
            = hidden_field_tag :cmd, "_s-xclick"
            = hidden_field_tag :encrypted, current_user.paypal_encrypted("4 godziny prywatnej lekcji", CONST[:price_buy_order] * 16 , current_user , root_url, payment_notifications_url(:secret =>  CONFIG[:paypal_secret], :tokens => 4))
            = submit_tag "Kup", class: "btn square" 

  .clear