config/routes.rb
Korepetytor::Application.routes.draw do

 

  devise_for :users , :path => 'konto' #TODO: nazwy akcji 
     
  
  resources :users, :path => "uzytkownik",  :only => [] do
    resources :comments,  :path => "komentarze", :only => [:update, :edit, :index], :path_names => { :edit => "wystaw" } 
    resource :room,  :path => "pokoj"
    resource :tutor ,  :path => "korepetytor", :path_names => { :new => "zostan", :edit => "edytuj" } 
    resources :payment_histories, :only => [:create]
    resource :payment_management,  :path => "moje_platnosci", :only => [:show]
    resource :my_profile, :path => "moj_profil", :only => :show
  end
 
  resources :messages, :only => [:create]
  resources :contacts, :only => [:create]

  resources :tutors, :path => "korepetytor", :only => [:show] do
    resource :private_room, :path => "prywatna_lekcja" do
      member do
        get :annouce
      end
    end
    resources :comments,  :path => "komentarze",  :only => [:index]
    member do
      put :online
    end
    
  end
  
  resources :subjects, :path => "przedmioty", :only => [:index, :show] do
    resources :tutors, :path => "korepetytorzy", :only => [:index]
  end
  
  resources :payment_notifications, :only => :create

  resources :search_resoults, :path => "szukam", :only => [:index]

  resources :welcomes, :path => "jaktodziala", :only => [:index]

  root :to => 'subjects#index'

end

app/views/shared/_annouce_content.html.haml
.roomAnnouce
  Korepetytor utworzył lekcję dla użytkownika 
  %strong
    = learner.nickname
  .alertLink.center
    #{learner.nickname} przejdź do prywatnej lekcji 
    =link_to "klikając tutaj!", tutor_private_room_path(tutor)

app/views/shared/_chat_sender.html.haml
.input-append
  - if user_signed_in?
    = form_for( Message.new, remote: true ,   :url => {:controller => "/messages", :action => "create" , :room => room, :control => (room.instance_of?(Room) ? "pub" : "priv")}) do |f| 
      = f.text_field :content, id: "fixSendMessage" #, :placeholder => "Porozmawiaj na czacie"
      = f.submit "Wyślij" , class: "btn square"
  - else
    = form_for( "#", :method => :get) do |f| 
      = f.text_field :nothing, :id => "fixSendMessage",  :disabled => true , :placeholder => "Aby pisać na czacie musisz się zalogować"
      = f.submit "Wyślij" , :disabled => true , class: "btn square"  

= subscribe_to "/messages/private/#{room.sessionId}"
        

app/views/shared/_generate_video.js.erb
TB.setLogLevel(TB.DEBUG);

var apiKey = "<%=  CONFIG[:api_key] %>"; 
var sessionId = "<%= room.sessionId %>"; 
var token = "<%= ot_token %>"; 
var viewForLearner
<%- if room.instance_of? (PrivateRoom)  and current_user != room.tutor.user %>
viewForLearner = true ; 
<% end %>

<%- if room.instance_of? (PrivateRoom)   %>
var tutor = false; 
<% else %>
var tutor = "<%=  room.user.tutor.id %>"; 
<% end %>

$(document).ready(function(){
   connect();
});

app/views/shared/_subject_list.html.haml
.box.mini
  %strong
    Przedmioty:
  %ul
    - Subject.all_by_popularity.each do |subject|
      %li.boxElement
        = link_to "#{subject.name} (#{subject.tutor_subjects.size})",  subject_tutors_path(subject.id)
  .clear

app/views/shared/_video_buttons.html.haml
%input.fixBtnInline#connectLink{ :type => "button", :value => "Połącz", :class => "btn square"  }
%input.fixBtnInline#publishLink{ :type => "button", :value => "Zacznij nadawać", :class => "btn square"}
#radioGroup
  %label.radio.fixBtnInline
    %input#audVid{ name: "pubOpt", type: "radio", :checked => "checked" }
    Video + Audio
  %label.radio.fixBtnInline
    %input#vidOnly{ name: "pubOpt", type: "radio" }
    Video
  %label.radio.fixBtnInline
    %input#audOnly{ name: "pubOpt", type: "radio" }
    Audio
%input.fixBtnInline#unpublishLink{ :type => "button", :value => "Zakończ nadawanie", :class => "btn square"}
-#%input.fixBtnInline#disconnectLink{:onClick => "javascript:disconnect()", :type => "button", :value => "Przejdź w tryb offline"} 