config/routes.rb
Korepetytor::Application.routes.draw do

 

  devise_for :users , :path => 'konto' #TODO: nazwy akcji 
     
  
  resources :users, :path => "uzytkownik",  :only => [] do
    resources :comments,  :path => "komentarze", :only => [:update, :edit, :index], :path_names => { :edit => "wystaw" } 
    resource :room,  :path => "pokoj"
    resource :tutor ,  :path => "korepetytor", :path_names => { :new => "zostan", :edit => "edytuj" } 
    resources :payment_histories, :only => [:create]
    resource :payment_management,  :path => "moje_platnosci", :only => [:show]
    resource :my_profile, :path => "moj_profil", :only => :show
  end
 
  resources :messages, :only => [:create]
  resources :contacts, :only => [:create]

  resources :tutors, :path => "korepetytor", :only => [:show] do
    resource :private_room, :path => "prywatna_lekcja" do
      member do
        get :annouce
      end
    end
    resources :comments,  :path => "komentarze",  :only => [:index]
    member do
      put :online
    end
    
  end
  
  resources :subjects, :path => "przedmioty", :only => [:index, :show] do
    resources :tutors, :path => "korepetytorzy", :only => [:index]
  end
  
  resources :payment_notifications, :only => :create

  resources :search_resoults, :path => "szukam", :only => [:index]

  resources :welcomes, :path => "jaktodziala", :only => [:index]

  root :to => 'subjects#index'

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  sessionId  :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Room < ActiveRecord::Base
  
  begin :attributes
  attr_accessible :name, :sessionId
  end
  
  begin :validations
  validates :sessionId, :presence => true,  :uniqueness => true  
  validates :name,      :presence => true,  :uniqueness => true  
  end
  
  begin :relations
  belongs_to :user
  has_many :messages, :as => :conversation, :dependent => :destroy
  end

end

app/controllers/rooms_controller.rb
# encoding: utf-8
# #!/bin/env ruby
class RoomsController < ApplicationController
  before_filter :signed_in, :except => [ :show, :index ]
 
  def new
    user = find_user(params[:user_id])
    @room = user.build_room
    authorize!(:manage, @room)
  end
  
  def create
    user = find_user(params[:user_id])
    opentok = config_opentok
    session = opentok.create_session request.remote_addr
    params[:room][:sessionId] = session.session_id
    @room = user.build_room(params[:room])
    authorize!(:manage, @room)

    respond_to do |format|
      if @room.save
        format.html { redirect_to user_tutor_path(user) }
      else
        format.html { 
          flash[:error] = "Nieznany błąd, spróbuj ponownie."
          redirect_to new_user_room_path(user) } 
      end
    end
  end
  
  def show
    user = find_user(params[:user_id])
    @room = user.room
    @tutor = user.tutor
    opentok = config_opentok   
    @ot_token = opentok.generate_token( session_id: @room.sessionId, role: find_role(user), connection_data: find_role(user) )
    
    @learner =find_user(@tutor.private_room.learner_id) if @tutor.private_room.present? 
  end
  
  def edit
    user = find_user(params[:user_id])
    @room = user.room
    authorize!(:manage, @room)
  end
  
  def update
    user = find_user(params[:user_id])
    @room = user.room
    authorize!(:manage, @room)
    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to user_room_path(user) }
      else
        format.html { render :action => "edit" } 
      end
    end
  end

  
  private
  def config_opentok       
    opentok = OpenTok::OpenTokSDK.new CONFIG[:api_key], CONFIG[:api_secret]
    opentok #TODO: usunac to
  end
  
  def find_user(user_id)
    User.find(user_id)
  end

  def find_role(user)
    if current_user == user
      ot_role = "publisher"
    else
      ot_role = "subscriber"   
    end
    ot_role
  end
  
  def signed_in
    unless user_signed_in?
      flash[:notice] = "Aby kontynuować musisz się zalogować."
      redirect_to new_user_session_path
    end
  end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
=form_for(@room, :url => user_room_path(@room.user),  :html => { :class => "form-horizontal" }) do |f|
  .control-group.space
    =f.label :name, "Tytuł dla pokoju:", class: "control-label"
    .controls
      = f.text_area :name, :rows => 2
      = errors_for f, :name
  .control-group
    .controls
      = f.submit " #{params[:action] == "new" ? "Twórz Pokój" : "Zapisz zmiany"} ", class: "btn square"
      -if params[:action] == "edit"
        %small
          lub 
          =link_to "wróć do swojego pokoju", user_room_path(@room.user)

app/views/rooms/edit.html.haml
- content_for :title do
  Zmień Tytuł
.contentBackground.threeFourSize
  %legend
    Zmień tytuł swojego pokoju
  = render :partial => 'form'
  

app/views/rooms/new.html.haml
- content_for :title do
  Twórz Pokój
.contentBackground.threeFourSize
  %legend
    Krok 2 - Twórz Pokój
  .roomControl
    %small
      Twój Pokój będzie miejscem gdzie możesz czekać na uczniów i przeprowadzać wstępne rozmowy z nimi.
      %br
      Jeżeli przebywasz na stronie Twojego Pokoju, zmieniasz status na ONLINE.
      %br
      Dzięki statusowi ONLINE pojawiasz się w katalogu i wynikach wyszukiwania w pierwszej kolejności.
  .space.clear
  .roomControl
    %small
      Aby rozpocząć płatną lekcję z uczniem wystarczy kliknąć w "Twórz Płatną Lekcję" i wpisać nick ucznia.
      %br
      Uczeń dostanie informację o utworzonej lekcji, poczekaj aż dołączy do Ciebie.
      %br
      Poproś o zapłacenie za lekcję, po zapłaceniu pojawi się komunikat i uruchomi się licznik.
      %br
      Po skończonej lekcji poproś ucznia o wystawienie opini oraz usuń lekcje klikając w "Zakończ lekcję"
      %br
      Jeżeli wyjdziesz bez usuwania lekcji, zostanie ona skasowana automatycznie po upływie #{CONST[:priv_room_expire_in]}min.
  .space.clear
  .roomControl
    %small
      Im lepsze oceny i im więcej opiń tym lepsza pozycja w katalogu i w wynikach wyszukiwania
    
  .clear
  .dataBox
    %i  
    Możesz ustawić krótki tytuł, który będzie wyświetlany na stronie Twojego pokoju.
    = render :partial => 'form'
  .clear

app/views/rooms/show.html.haml
- content_for :title do
  ="Pokój użytkownika #{@tutor.user.nickname}"
:javascript
  #{ render :partial => "shared/generate_video.js", :locals => { :room => @room, :ot_token => @ot_token }}

.contentBackground
  #colLeft
    .avatar
      = image_tag @tutor.avatar.url(:medium) 
    #roomTitle 
      = @tutor.user.nickname
      = link_to "O mnie", user_tutor_path(@tutor.user)
    #roomDescription
      = @room.name
      - if can? :manage, @room
        %small
          =link_to "Zmień", edit_user_room_path(@tutor.user)
    .clear
    #roomContent
      #privateRoomAnnouces
      - if @tutor.private_room.present? and can? :manage, @room
        .roomAnnouce 
          Utworzyłeś płatną lekcję z użytkownikiem 
          %strong=@learner.nickname
          %small
            =link_to "Usuń!", tutor_private_room_path(@tutor) , :method => :delete, confirm: "Jestes pewien?" 
          .alertLink.center
            =link_to "Przejdź do płatnej lekcji", tutor_private_room_path(@tutor)      
      - elsif can? :manage, @room
        .roomAnnouce
          %small
            Po wstępnej rozmowie możesz utworzyć płatną lekcję z jednym z użytkowników.
            %br
            Zapamiętaj jego nick i 
          =link_to "stwórz płatną lekcję", new_tutor_private_room_path(@tutor)         

      - elsif @tutor.private_room.present?
        = render :partial => 'shared/annouce_content', :locals => { :learner => @learner, :tutor => @room.user.tutor } 
    .clear

      #videobox
      = render :partial => 'tutors/profile_information', :locals => { :tutor => @tutor }




  #colRight
    .roomControl
      Status połączenia: 
      %span#connectionStatus
    - if can? :manage, @room
      .clear
      = render :partial => 'shared/video_buttons'  

    .clear
    #chatHeader
      %h5
        CZAT
      = render :partial => 'shared/chat_sender', :locals => { :room => @room }

 

    %ul#chat
  .clear
    